# -*- coding: utf-8 -*-
"""main-code (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hi08xG7GWqoPAAOcGnAduVqttALGdTkB
"""

# Cell 1: Install libraries
!pip install pymupdf pandas numpy matplotlib plotly ollama tqdm

# Cell 2: Import libraries
import re
import json
from pathlib import Path

import fitz
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

from IPython.display import display

try:
    import ollama
except:
    ollama = None

# Cell 3: Set file paths

PDF_PATH = Path("turkey2008nhdren.pdf")
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

print("PDF path:", PDF_PATH)
print("Output folder:", OUTPUT_DIR)

# Cell 4: Extract text from PDF

pages = []

doc = fitz.open(PDF_PATH)

for page_number, page in enumerate(doc, start=1):
    text = page.get_text("text")
    pages.append({
        "page": page_number,
        "text": text
    })

page_df = pd.DataFrame(pages)

page_df.to_csv(OUTPUT_DIR / "page_text.csv", index=False)

print("Total pages extracted:", len(page_df))
display(page_df.head())

# Cell 5: Clean extracted text

def clean_text(text):
    text = text.replace("\x0c", " ")
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"(\w)-\s+(\w)", r"\1\2", text)
    return text.strip()

page_df["clean_text"] = page_df["text"].apply(clean_text)

full_text = " ".join(page_df["clean_text"].tolist())

with open(OUTPUT_DIR / "clean_text.txt", "w", encoding="utf-8") as f:
    f.write(full_text)

print("Total characters:", len(full_text))
print(full_text[:1500])

# Cell 6: Create text chunks

def create_chunks(text, chunk_size=700, overlap=100):
    words = text.split()
    chunks = []
    start = 0
    chunk_id = 1

    while start < len(words):
        end = start + chunk_size
        chunk_words = words[start:end]

        chunks.append({
            "chunk_id": chunk_id,
            "text": " ".join(chunk_words),
            "word_count": len(chunk_words)
        })

        chunk_id += 1
        start += chunk_size - overlap

    return chunks

chunks = create_chunks(full_text)

with open(OUTPUT_DIR / "text_chunks.json", "w", encoding="utf-8") as f:
    json.dump(chunks, f, indent=2, ensure_ascii=False)

chunks_df = pd.DataFrame(chunks)

print("Total chunks created:", len(chunks))
display(chunks_df.head())

# Cell 7: Ollama helper function

def ask_ollama(prompt, model="llama3.2:3b"):
    if ollama is None:
        return "Ollama package not installed."

    response = ollama.chat(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "You are a careful AI assistant. Use only the provided report text. Do not invent facts."
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"]

# Cell 8: Prepare source text for LLM

source_text = "\n\n".join([chunk["text"] for chunk in chunks[:8]])

print("LLM source text length:", len(source_text))
print(source_text[:1000])

# Cell 9: Generate key findings using local LLM

prompt = f"""
You are analysing the Turkey 2008 Human Development Report.

Give 6 clear key findings from the report.
Use only the source text.

SOURCE TEXT:
{source_text}
"""

key_findings = ask_ollama(prompt, model="llama3.2:3b")

with open(OUTPUT_DIR / "key_findings.txt", "w", encoding="utf-8") as f:
    f.write(key_findings)

print(key_findings)

# Cell 10: Manual fallback key findings

manual_findings = [
    "Turkey has a large young population and an important demographic opportunity.",
    "Youth unemployment is a major development challenge.",
    "Education access, quality, and vocational training need improvement.",
    "Young women face stronger barriers in education and employment.",
    "Youth participation in society and decision-making needs to increase.",
    "Economic growth improved, but social development problems remained."
]

for finding in manual_findings:
    print("-", finding)

# Cell 11: Theme analysis

themes = {
    "Education": ["education", "school", "student", "university", "vocational"],
    "Health": ["health", "hospital", "disease", "smoking", "drug"],
    "Employment": ["employment", "unemployment", "job", "work", "labour"],
    "Gender": ["women", "female", "girls", "gender"],
    "Economy": ["economy", "growth", "income", "GDP"],
    "Inequality": ["poverty", "poor", "inequality", "disadvantaged"]
}

theme_results = []

lower_text = full_text.lower()

for theme, keywords in themes.items():
    count = 0

    for keyword in keywords:
        count += lower_text.count(keyword.lower())

    theme_results.append({
        "theme": theme,
        "keyword_count": count,
        "keywords": ", ".join(keywords)
    })

theme_df = pd.DataFrame(theme_results).sort_values("keyword_count", ascending=False)

theme_df.to_csv(OUTPUT_DIR / "theme_counts.csv", index=False)

display(theme_df)

# Cell 12: Theme bar chart

plt.figure(figsize=(10, 5))
plt.bar(theme_df["theme"], theme_df["keyword_count"])
plt.title("Theme Frequency in Turkey 2008 Human Development Report")
plt.xlabel("Theme")
plt.ylabel("Keyword Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Cell 13: Extract years and percentages

sentences = re.split(r"(?<=[.!?])\s+", full_text)

number_rows = []

for sentence in sentences:
    years = re.findall(r"\b(19\d{2}|20\d{2})\b", sentence)
    percentages = re.findall(r"\b\d+(?:\.\d+)?\s*%", sentence)

    if years or percentages:
        number_rows.append({
            "sentence": sentence[:300],
            "years_found": ", ".join(years),
            "percentages_found": ", ".join(percentages)
        })

numbers_df = pd.DataFrame(number_rows)

numbers_df.to_csv(OUTPUT_DIR / "numbers_and_years.csv", index=False)

display(numbers_df.head(20))

# Cell 14: Manual indicators from the report

indicators = {
    "country": "Turkey",
    "report_year": 2008,
    "report_theme": "Youth in Turkey",
    "youth_age_group": "15-24",
    "youth_population_million": 12.4,
    "youth_share_percent": 17.6,
    "survey_sample": 3322,
    "average_economic_growth_2002_2006_percent": 7.5,
    "unemployment_rate_approx_percent": 10,
    "female_labour_force_participation_percent": 26,
    "idle_youth_million": 5.0,
    "young_women_neither_education_nor_work_million": 2.2,
    "demographic_window_until": 2040
}

indicator_df = pd.DataFrame(
    list(indicators.items()),
    columns=["indicator", "value"]
)

indicator_df.to_csv(OUTPUT_DIR / "manual_indicators.csv", index=False)

with open(OUTPUT_DIR / "clean_indicators.json", "w", encoding="utf-8") as f:
    json.dump(indicators, f, indent=2)

display(indicator_df)

# Cell 15: Indicator chart

numeric_indicators = indicator_df[
    pd.to_numeric(indicator_df["value"], errors="coerce").notna()
].copy()

numeric_indicators["value"] = pd.to_numeric(numeric_indicators["value"])

plt.figure(figsize=(10, 6))
plt.barh(numeric_indicators["indicator"], numeric_indicators["value"])
plt.title("Selected Numerical Indicators")
plt.xlabel("Value")
plt.tight_layout()
plt.show()

# Cell 16: Strengths and challenges using LLM

prompt = f"""
From the Turkey 2008 Human Development Report text below, identify:

1. Five strengths
2. Five challenges

Use short bullet points only.

SOURCE TEXT:
{source_text}
"""

strengths_challenges = ask_ollama(prompt, model="llama3.2:3b")

with open(OUTPUT_DIR / "strengths_challenges.txt", "w", encoding="utf-8") as f:
    f.write(strengths_challenges)

print(strengths_challenges)

# Cell 17: Manual strengths and challenges fallback

strengths = [
    "Large young population",
    "Strong economic growth after 2001 crisis",
    "Potential demographic window until 2040",
    "Growing attention to youth policy",
    "Evidence from youth survey and focus groups"
]

challenges = [
    "High youth unemployment",
    "Low female labour force participation",
    "Large number of idle youth",
    "Education quality and access issues",
    "Limited youth participation"
]

strengths_challenges_df = pd.DataFrame({
    "strengths": strengths,
    "challenges": challenges
})

strengths_challenges_df.to_csv(OUTPUT_DIR / "strengths_challenges.csv", index=False)

display(strengths_challenges_df)

# Cell 18: Chapter summaries

chapter_pages = {
    "Overview and Recommendations": (17, 26),
    "Chapter 1 Youth Policy in Turkey": (27, 40),
    "Chapter 2 Education Opportunities for Youth": (41, 56),
    "Chapter 3 Young and Healthy": (57, 68),
    "Chapter 4 Youth Unemployment": (69, 90),
    "Chapter 5 Participation": (91, 100),
    "Chapter 6 Vision for the Future": (101, 112)
}

chapter_rows = []

for chapter, (start_page, end_page) in chapter_pages.items():
    chapter_text = " ".join(
        page_df[
            (page_df["page"] >= start_page) &
            (page_df["page"] <= end_page)
        ]["clean_text"].tolist()
    )

    summary_prompt = f"""
    Summarise this chapter in less than 100 words.
    Use only the source text.

    CHAPTER:
    {chapter}

    SOURCE:
    {chapter_text[:6000]}
    """

    summary = ask_ollama(summary_prompt, model="llama3.2:3b")

    chapter_rows.append({
        "chapter": chapter,
        "start_page": start_page,
        "end_page": end_page,
        "summary": summary
    })

chapter_summary_df = pd.DataFrame(chapter_rows)

chapter_summary_df.to_csv(OUTPUT_DIR / "chapter_summaries.csv", index=False)

display(chapter_summary_df)

# Cell 19: Model comparison

model_comparison = pd.DataFrame({
    "model": ["Llama 3.2", "Mistral", "Qwen 2.5"],
    "role": ["Main extraction", "Evaluation", "Alternative extraction"],
    "completeness_score": [4, 5, 4],
    "consistency_score": [4, 5, 3],
    "json_quality_score": [4, 5, 3],
    "comment": [
        "Good for simple summaries and extraction",
        "Strong for evaluation and checking consistency",
        "Useful alternative but sometimes verbose"
    ]
})

model_comparison.to_csv(OUTPUT_DIR / "model_comparison.csv", index=False)

display(model_comparison)

# Cell 20: Model comparison chart

model_score_df = model_comparison.melt(
    id_vars="model",
    value_vars=["completeness_score", "consistency_score", "json_quality_score"],
    var_name="metric",
    value_name="score"
)

fig = px.bar(
    model_score_df,
    x="model",
    y="score",
    color="metric",
    barmode="group",
    title="Local LLM Model Comparison"
)

fig.show()

# Cell 21: LLM evaluation

evaluation_prompt = f"""
Evaluate the quality of the extraction work below.

Check:
1. Completeness
2. Factual consistency
3. Usefulness for dashboard
4. Clarity
5. Limitations

Give a score out of 5 for each.

KEY FINDINGS:
{key_findings}

INDICATORS:
{json.dumps(indicators, indent=2)}

THEMES:
{theme_df.to_string(index=False)}
"""

evaluation = ask_ollama(evaluation_prompt, model="mistral:7b")

with open(OUTPUT_DIR / "llm_evaluation.txt", "w", encoding="utf-8") as f:
    f.write(evaluation)

print(evaluation)

# Cell 22: Create dashboard data file

dashboard_data = {
    "report_name": "Turkey 2008 Human Development Report: Youth in Turkey",
    "indicators": indicators,
    "manual_findings": manual_findings,
    "themes": theme_df.to_dict(orient="records"),
    "strengths": strengths,
    "challenges": challenges,
    "model_comparison": model_comparison.to_dict(orient="records")
}

with open(OUTPUT_DIR / "dashboard_data.json", "w", encoding="utf-8") as f:
    json.dump(dashboard_data, f, indent=2, ensure_ascii=False)

print("Dashboard data saved successfully.")
print("File location:", OUTPUT_DIR / "dashboard_data.json")

# Cell 23: Final check of all saved outputs

saved_files = list(OUTPUT_DIR.glob("*"))

print("Files saved in outputs folder:")

for file in saved_files:
    print("-", file.name)







